//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://schemas.datacontract.org/2004/07/SOAPServer")]
    public partial class Libro : object
    {
        
        private string AutorField;
        
        private int AñoPublicacionField;
        
        private int IdField;
        
        private string TituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor
        {
            get
            {
                return this.AutorField;
            }
            set
            {
                this.AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AñoPublicacion
        {
            get
            {
                return this.AñoPublicacionField;
            }
            set
            {
                this.AñoPublicacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.IBookService")]
    public interface IBookService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/CrearLibro", ReplyAction="http://tempuri.org/IBookService/CrearLibroResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Libro> CrearLibroAsync(BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerLibro", ReplyAction="http://tempuri.org/IBookService/ObtenerLibroResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Libro> ObtenerLibroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerTodosLosLibros", ReplyAction="http://tempuri.org/IBookService/ObtenerTodosLosLibrosResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Libro[]> ObtenerTodosLosLibrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ActualizarLibro", ReplyAction="http://tempuri.org/IBookService/ActualizarLibroResponse")]
        System.Threading.Tasks.Task<BookServiceReference.Libro> ActualizarLibroAsync(BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/EliminarLibro", ReplyAction="http://tempuri.org/IBookService/EliminarLibroResponse")]
        System.Threading.Tasks.Task<bool> EliminarLibroAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IBookServiceChannel : BookServiceReference.IBookService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<BookServiceReference.IBookService>, BookServiceReference.IBookService
    {
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Libro> CrearLibroAsync(BookServiceReference.Libro libro)
        {
            return base.Channel.CrearLibroAsync(libro);
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Libro> ObtenerLibroAsync(int id)
        {
            return base.Channel.ObtenerLibroAsync(id);
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Libro[]> ObtenerTodosLosLibrosAsync()
        {
            return base.Channel.ObtenerTodosLosLibrosAsync();
        }
        
        public System.Threading.Tasks.Task<BookServiceReference.Libro> ActualizarLibroAsync(BookServiceReference.Libro libro)
        {
            return base.Channel.ActualizarLibroAsync(libro);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarLibroAsync(int id)
        {
            return base.Channel.EliminarLibroAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
