//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPCliente.BookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://schemas.datacontract.org/2004/07/SOAPServer")]
    [System.SerializableAttribute()]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AñoPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AñoPublicacion {
            get {
                return this.AñoPublicacionField;
            }
            set {
                if ((this.AñoPublicacionField.Equals(value) != true)) {
                    this.AñoPublicacionField = value;
                    this.RaisePropertyChanged("AñoPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookServiceReference.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/CrearLibro", ReplyAction="http://tempuri.org/IBookService/CrearLibroResponse")]
        SOAPCliente.BookServiceReference.Libro CrearLibro(SOAPCliente.BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/CrearLibro", ReplyAction="http://tempuri.org/IBookService/CrearLibroResponse")]
        System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> CrearLibroAsync(SOAPCliente.BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerLibro", ReplyAction="http://tempuri.org/IBookService/ObtenerLibroResponse")]
        SOAPCliente.BookServiceReference.Libro ObtenerLibro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerLibro", ReplyAction="http://tempuri.org/IBookService/ObtenerLibroResponse")]
        System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> ObtenerLibroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerTodosLosLibros", ReplyAction="http://tempuri.org/IBookService/ObtenerTodosLosLibrosResponse")]
        SOAPCliente.BookServiceReference.Libro[] ObtenerTodosLosLibros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ObtenerTodosLosLibros", ReplyAction="http://tempuri.org/IBookService/ObtenerTodosLosLibrosResponse")]
        System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro[]> ObtenerTodosLosLibrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ActualizarLibro", ReplyAction="http://tempuri.org/IBookService/ActualizarLibroResponse")]
        SOAPCliente.BookServiceReference.Libro ActualizarLibro(SOAPCliente.BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ActualizarLibro", ReplyAction="http://tempuri.org/IBookService/ActualizarLibroResponse")]
        System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> ActualizarLibroAsync(SOAPCliente.BookServiceReference.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/EliminarLibro", ReplyAction="http://tempuri.org/IBookService/EliminarLibroResponse")]
        bool EliminarLibro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/EliminarLibro", ReplyAction="http://tempuri.org/IBookService/EliminarLibroResponse")]
        System.Threading.Tasks.Task<bool> EliminarLibroAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : SOAPCliente.BookServiceReference.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<SOAPCliente.BookServiceReference.IBookService>, SOAPCliente.BookServiceReference.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPCliente.BookServiceReference.Libro CrearLibro(SOAPCliente.BookServiceReference.Libro libro) {
            return base.Channel.CrearLibro(libro);
        }
        
        public System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> CrearLibroAsync(SOAPCliente.BookServiceReference.Libro libro) {
            return base.Channel.CrearLibroAsync(libro);
        }
        
        public SOAPCliente.BookServiceReference.Libro ObtenerLibro(int id) {
            return base.Channel.ObtenerLibro(id);
        }
        
        public System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> ObtenerLibroAsync(int id) {
            return base.Channel.ObtenerLibroAsync(id);
        }
        
        public SOAPCliente.BookServiceReference.Libro[] ObtenerTodosLosLibros() {
            return base.Channel.ObtenerTodosLosLibros();
        }
        
        public System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro[]> ObtenerTodosLosLibrosAsync() {
            return base.Channel.ObtenerTodosLosLibrosAsync();
        }
        
        public SOAPCliente.BookServiceReference.Libro ActualizarLibro(SOAPCliente.BookServiceReference.Libro libro) {
            return base.Channel.ActualizarLibro(libro);
        }
        
        public System.Threading.Tasks.Task<SOAPCliente.BookServiceReference.Libro> ActualizarLibroAsync(SOAPCliente.BookServiceReference.Libro libro) {
            return base.Channel.ActualizarLibroAsync(libro);
        }
        
        public bool EliminarLibro(int id) {
            return base.Channel.EliminarLibro(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarLibroAsync(int id) {
            return base.Channel.EliminarLibroAsync(id);
        }
    }
}
